name: Prepare Release (Modular)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in major.minor.patch format'
        required: true
        type: string

jobs:
  validate_version:
    name: Validate version number
    uses: ehennestad/matbox/.github/workflows/reusable-job_validate-version.yml@make-release-workflow-reusable
    with:
      version: ${{ inputs.version }}
      ref_name: ${{ github.ref_name }}
      tools_directory: tests

  build_matrix:
    name: Build release test matrix
    uses: ehennestad/matbox/.github/workflows/reusable-job_build-matrix.yml@make-release-workflow-reusable
    with:
      tools_directory: tests
      needs_python: false

  test:
    name: Run MATLAB tests
    needs: [validate_version, build_matrix]
    uses: ehennestad/matbox/.github/workflows/reusable-job_run-tests.yml@make-release-workflow-reusable
    with:
      code_directory: +ndi
      tools_directory: tests
      matlab_products: ''
      needs_python: false
      matrix_json: ${{ needs.build_matrix.outputs.matrix }}

  release:
    name: Package toolbox and create draft release
    needs: [test, validate_version]
    uses: ehennestad/matbox/.github/workflows/reusable-job_package-toolbox.yml@make-release-workflow-reusable
    with:
      version_number: ${{ needs.validate_version.outputs.version_number }}
      code_directory: +ndi
      tools_directory: tests
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  verify_installation:
    name: Verify toolbox installation
    needs: [release, validate_version]
    uses: ehennestad/matbox/.github/workflows/reusable-job_verify-installation.yml@make-release-workflow-reusable
    with:
      toolbox_name: ${{ needs.release.outputs.toolbox_name }}
